version: '3.9'

services: 
    # MongoDB service
    mongo_db:
        container_name: booksearch-db-c
        image: mongo:latest
        restart: always
        ports:
            - 2717:27017
        volumes:
            - mongo_db:/data/db

    # Node API servcie
    api:
        build: .
        ports:
            - 3000:3000
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
        container_name: booksearch-api-c
        environment: 
            PORT: ${PORT}
            MONGODB_URL: mongodb://mongo_db:27017
            DB_NAME: ${DB_NAME}
            accessTokenKey: ${accessTokenKey}
            refreshTokenKey: ${refreshTokenKey}
            ITBOOKSTORE_API_URL: ${ITBOOKSTORE_API_URL}
        depends_on: 
            - mongo_db

volumes:
    mongo_db: {}